# **G345 ANÁLISIS DE DATOS**

# Nombre del proyecto

### Nombre y cédula de los integrantes

- Ximena Orbes Arias - 1033099573

- Juan Esteban Lame Vasquez - 1142514863

- Isabella Cardona Betancourt

- Meycol Kleym Quintero Castaño

## Base de datos: Tarifas y Costos de Energía Eléctrica para el Mercado Regulado

En cumplimiento de las Leyes 142 de 1994 y 1955 de 2019, y las Resoluciones CREG (Comisión de Regulación de Energía y Gas) 058 de 2000, 119 de 2007, 105 de 2009, 156 de 2009, 173 de 2011, 152 de 2018 y 101028 de 2023, este conjunto de datos proporciona información detallada sobre las tarifas y costos de energía eléctrica en el mercado regulado.

Los datos incluyen información sobre las tarifas de energía, el costo de compra de energía, los cargos de transporte en los sistemas de transmisión y distribución, los márgenes de comercialización, costos relacionados con generación y pérdidas, así como otros factores operativos que influyen en el precio final que los usuarios deben pagar. Además, se desglosan por tipo de propiedad (Operador de Red, Propiedad Compartida, Propiedad Cliente) y se dividen en diferentes niveles de tensión eléctrica.

Este conjunto de datos está diseñado para facilitar el análisis de las tarifas y costos eléctricos en distintas regiones y periodos, proporcionando una visión clara de los componentes que afectan el precio de la energía para los usuarios del mercado regulado.

Los datos abarcan el periodo de enero de 2024 a septiembre de 2025.

## Diccionario de datos

- *Año:* El año en el que se registran los datos sobre tarifas y costos de energía eléctrica. Ejemplo: 2024
- *Priodo:* El mes o período específico dentro del año al que corresponde la tarifa o costo de energía.
- *Operador de red:* La empresa responsable de la distribución de energía eléctrica en una zona específica.
- *Nivel:* La categoría del servicio eléctrico, que puede incluir diferentes tipos de tensión como Baja Tensión (B.T.), Media Tensión (M.T.) o Alta Tensión (A.T.).
- *CU Total:* El costo total por kilovatio hora (kWh) que los usuarios deben pagar por la electricidad, incluyendo todos los cargos.
- *Costo Compra (Gm,i):* El precio que paga el operador de red por la electricidad comprada a los generadores.
- *Cargo Transporte STN (Tm):* El costo asociado al transporte de electricidad a través del Sistema de Transmisión Nacional (STN), que es la red de alta tensión que lleva la electricidad de los generadores a las subestaciones.
- *Cargo Transporte SDL (Dn,m):* El costo asociado al transporte de electricidad en el Sistema de Distribución Local (SDL), que distribuye la electricidad desde las subestaciones hasta los usuarios finales.
- *Margen Comercialización (CVm,i,j):* El costo adicional que cubre la comercialización de la electricidad, incluyendo los gastos de operación y transacción del operador de red.
- *Costo G, T, Pérdidas (PRn,m):* Los costos asociados a la generación, transmisión y pérdidas de energía durante su transporte por la red, debido a la resistencia y otros factores.
- *Restricciones (Rm):*Costos adicionales que surgen debido a las restricciones técnicas o de operación en la red eléctrica.
- *COT:* El Costo de Operación y Transporte, que incluye los costos operativos y de transporte de electricidad en diferentes niveles de tensión.
- *Cfm,j ($/fact.):* 	
El costo fijo mensual por factura que los usuarios deben pagar, independientemente de la cantidad de electricidad que consuman.

# Análisis de datos

## Preguntas a responder con la base de datos

¿El aumento del CU está más asociado al costo de compra de energía o a ineficiencias de transporte y pérdidas?

¿Existen operadores con márgenes de comercialización atípicos frente al resto del mercado?

¿Qué operadores presentan mayor riesgo de incrementos tarifarios abruptos?

¿Qué operadores requieren intervención regulatoria por ineficiencia estructural?

## Carga del archivo CSV

In [65]:
import pandas as pd
import numpy as np
from pathlib import Path

# Ruta relativa: este notebook está en la misma carpeta que DATASET.csv
ruta_csv = Path(r"C:\Users\Flia_Orbes\Análisis de datos\Proyecto_AnalisisDeDatos-1\Proyecto\Tarifas_y_Costos_de_Energía_Eléctrica_para_el_Mercado_Regulado.csv")

try:
    if not ruta_csv.exists():
        raise FileNotFoundError(f"No se encontró el archivo: {ruta_csv.resolve()}")
    df = pd.read_csv(ruta_csv, low_memory=False)
except (OSError, FileNotFoundError) as err:
    print(f"No se pudo abrir el archivo. Error: {err}.")
else:
    print("Archivo cargado con éxito en el dataframe.")
    print("Dimensiones:", df.shape)
    display(df.head())

Archivo cargado con éxito en el dataframe.
Dimensiones: (415, 13)

,Año,Periodo,Operador de red,Nivel,CU Total,"Costo Compra (Gm,i)",Cargo Transporte STN (Tm),"Cargo Transporte SDL (Dn,m)","Margen Comercialización (CVm,i,j)","Costo G, T, Pérdidas (PRn,m)",Restricciones (Rm),COT,"Cfm,j ($/fact.)"
0,"2,025",Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad OR),810.46,372.46,56.03,280.91,24.86,72.49,3.71,0.00,9.813
1,"2,025",Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad Compartida),787.37,372.46,56.03,257.82,24.86,72.49,3.71,0.00,9.813
2,"2,025",Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad Cliente),764.29,372.46,56.03,234.73,24.86,72.49,3.71,0.00,9.813
3,"2,025",Enero,ENEL Bogotá - Cundinamarca,NIVEL II,691.89,372.46,56.03,168.80,66.56,24.32,3.71,41.70,9.813
4,"2,025",Enero,ENEL Bogotá - Cundinamarca,NIVEL III,633.3,372.46,56.03,113.66,63.79,23.65,3.71,38.93,9.813

## Limpieza y preparación de datos

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Año                                415 non-null    object
 1   Periodo                            415 non-null    object
 2   Operador de red                    415 non-null    object
 3   Nivel                              415 non-null    object
 4   CU Total                           415 non-null    object
 5   Costo Compra (Gm,i)                415 non-null    float64
 6   Cargo Transporte STN (Tm)          415 non-null    float64
 7   Cargo Transporte SDL (Dn,m)        415 non-null    float64
 8   Margen Comercialización (CVm,i,j)  415 non-null    float64
 9   Costo G, T, Pérdidas (PRn,m)       415 non-null    float64
 10  Restricciones (Rm)                 415 non-null    float64
 11  COT                                415 non-null    float64
 12  Cfm,j ($/fact.)                    415 non-null    object
dtypes: float64(7), object(6)
memory usage: 42.3+ KB

In [47]:
df.dtypes

Año                                   object
Periodo                               object
Operador de red                       object
Nivel                                 object
CU Total                              object
Costo Compra (Gm,i)                  float64
Cargo Transporte STN (Tm)            float64
Cargo Transporte SDL (Dn,m)          float64
Margen Comercialización (CVm,i,j)    float64
Costo G, T, Pérdidas (PRn,m)         float64
Restricciones (Rm)                   float64
COT                                  float64
Cfm,j ($/fact.)                       object
dtype: object

In [60]:
for var in df.columns:
    df[var].nunique() 
    print(f"{var} [n = {df[var].nunique()}]: {df[var].unique()}\n")

Año [n = 2]: ['2,025' '2,024']

Periodo [n = 12]: ['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']

Operador de red [n = 6]: ['ENEL Bogotá - Cundinamarca' 'CELSIA Colombia - Valle del Cauca'
 'CELSIA Colombia - Tolima' 'EMCALI - Cali' 'CELSIA - Valle del Cauca'
 'CELSIA - Tolima']

Nivel [n = 7]: ['Nivel 1 (Propiedad OR)' 'Nivel 1 (Propiedad Compartida)'
 'Nivel 1 (Propiedad Cliente)' 'NIVEL II' 'NIVEL III'
 'Nivel 1 ( Propiedad OR )' 'Nivel 1  (Propiedad Cliente)']

CU Total [n = 412]: [ 810.46  787.37  764.29  691.89  633.3   841.    806.28  771.56  710.68
  601.84  937.62  886.89  836.15  684.1   619.58  783.82  768.02  752.22
  638.6   747.41  724.67  701.93  610.25  562.22  793.95  757.54  721.13
  657.13  590.36  795.88  743.64  691.4   650.2   593.3   746.4   724.88
  703.36  609.99  544.59  770.93  748.07  725.21  651.66  609.7   871.16
  834.73  798.3   722.54  624.62  878.96  826.83  774.7   650.27  593.34
  758.19  736.67  715.16  610.29  541.93  797.16  774.09  751.03  668.3
  609.82  874.75  838.24  801.74  731.15  616.7   905.55  853.3   801.06
  669.37  607.92  772.47  750.9   729.32  623.83  552.9   802.68  780.27
  757.85  669.64  598.57  818.78  783.86  748.93  680.5   578.85  910.03
  858.79  807.54  670.45  607.91  762.11  746.35  730.59  618.06  551.5
  864.28  841.89  819.5   738.16  664.51  886.83  852.17  817.51  743.46
  654.58  896.29  845.46  794.63  663.54  604.45  826.58  810.91  795.23
  688.42  622.19  741.85  719.5   697.16  624.91  571.55  773.47  739.44
  705.4   631.79  541.47  930.58  880.74  830.9   698.07  639.54  710.54
  695.09  679.64  571.79  507.13  757.55  735.14  712.72  637.19  577.78
  788.83  754.74  720.65  647.94  556.39  932.1   882.09  832.08  698.58
  636.58  705.24  689.84  578.58  516.59  765.4   742.94  720.48  643.89
  577.71  790.11  755.8   721.49  648.98  549.58  939.79  889.67  839.55
  699.31  634.72  734.25  718.81  703.37  585.16  522.19  764.32  742.01
  719.69  635.07  566.75  777.48  743.41  709.33  647.09  553.33  927.13
  877.55  827.97  685.14  624.27  711.6   696.27  680.94  581.22  515.89
  799.4   776.93  754.46  667.37  596.22  818.93  784.62  750.32  679.9
  588.13  924.51  874.59  824.68  681.09  621.16  755.33  739.87  724.41
  617.84  549.64  815.65  793.05  770.46  691.63  632.35  845.47  811.14
  572.6   776.81  700.5   605.45  912.02  861.9   811.78  678.45  614.25
  782.78  767.24  751.7   636.1   568.66  812.67  789.78  766.9   673.27
  605.18  823.22  788.6   753.98  679.85  588.54  933.07  882.52  831.96
  685.11  618.64  760.12  744.41  728.7   613.14  550.49  808.93  785.72
  762.51  701.31  640.79  861.8   826.69  791.57  712.84  589.17  914.66
  863.72  812.79  672.9   608.31  799.67  783.77  767.88  654.62  584.65
  825.05  799.13  773.2   715.29  639.22  870.83  835.29  799.75  750.87
  589.2   966.34  913.82  861.29  717.43  649.14  803.12  787.2   771.29
  654.29  584.96  809.95  783.42  756.89  696.71  625.32  830.35  795.31
  760.26  627.1   564.78  978.14  931.07  884.01  728.54  656.11  758.87
  744.75  730.63  618.77  558.66  740.97  714.33  687.7   632.09  565.44
  768.03  732.66  697.29  566.01  503.94  992.77  945.35  897.94  740.13
  670.03  690.29  676.03  661.77  558.06  497.89  717.06  690.71  625.83
  564.37  769.23  733.83  698.42  570.79  508.39 1003.57  956.21  908.85
  742.27  672.59  698.06  683.84  669.62  561.76  501.26  785.65  759.46
  733.27  676.97  604.33  819.88  784.66  749.44  615.63  550.91 1020.65
  973.63  926.6   772.5   700.91  749.95  735.76  721.57  609.77  547.12
  781.04  754.75  728.46  672.08  609.07  726.74  691.37  615.26  552.08
 1013.17  965.91  918.64  768.83  697.05  748.98  734.7   720.42  608.91
  547.8   781.48  755.07  728.66  662.24  589.72  739.21  703.77  668.33
  600.26  535.33  725.89  711.54  697.2   593.75  530.9 ]

Costo Compra (Gm,i) [n = 73]: [372.46 374.18 310.82 372.78 289.09 293.46 295.82 346.81 349.91 310.57
 347.38 391.41 394.58 312.92 392.   291.69 294.56 308.41 292.22 296.26
 299.1  312.46 296.78 299.77 302.22 312.38 300.22 322.32 324.45 306.81
 322.71 356.82 359.95 314.69 357.4  367.28 369.77 312.89 367.74 345.07
 346.87 312.79 345.41 366.82 367.73 306.36 366.99 354.16 355.18 307.41
 354.35 310.1  311.17 307.43 310.3  265.06 266.   308.31 265.23 268.54
 269.3  307.03 269.68 300.8  300.4  306.54 301.72 300.59 308.84 301.56
 306.03 305.8  306.98]

Cargo Transporte STN (Tm) [n = 21]: [56.03 54.32 49.2  57.43 54.27 47.96 52.84 55.93 57.14 48.55 52.27 55.37
 58.19 49.85 56.28 62.2  56.76 54.69 53.84 56.93 51.66]

Cargo Transporte SDL (Dn,m) [n = 289]: [280.91 257.82 234.73 168.8  113.66 257.74 223.02 188.29 153.33  91.72
 230.17 179.44 241.95 226.15 256.98 234.24 211.5  158.35 110.75 261.91
 225.5  189.09 157.72  94.45 204.74 152.5  240.39 218.87 253.04 230.18
 207.32 161.69 114.02 279.57 243.13 206.7  163.81  97.6  200.91 148.78
 258.05 236.53 268.05 244.99 221.93 169.41 117.47 282.04 245.54 209.04
 166.49  97.78 215.81 163.57 260.47 238.9  266.13 243.72 221.3  164.65
 111.39 254.7  219.78 184.85 151.61  87.79 214.89 163.64 238.94 223.18
 257.12 212.34 161.31 111.37 251.44 216.78 182.12 153.09  89.52 206.29
 155.46 235.77 220.09 257.95 235.6  213.26 162.49 113.13 260.81 226.77
 192.74 153.34  90.78 208.1  158.26 245.36 229.91 266.32 243.9  221.49
 170.11 117.41 264.36 230.27 196.18 154.11  94.26 216.31 166.3  248.96
 233.56 265.55 243.09 220.63 167.84 112.58 261.35 227.05 149.51  89.04
 215.42 165.3  245.92 230.48 266.9  244.59 222.28 162.35 110.47 247.84
 213.76 179.69 150.99  87.9  217.32 167.74 232.51 217.18 264.6  242.13
 219.66 165.33 114.75 257.25 222.95 188.64 156.92  91.2  214.68 164.77
 241.79 226.34 263.15 240.56 217.96 170.73 115.89 265.73 231.4  197.07
 157.28  92.38 213.03 162.91 250.2  234.66 280.72 257.83 234.95 174.68
 117.64 264.32 229.7  195.08 153.8   93.58 230.16 179.61 248.62 232.91
 272.98 249.77 226.56 172.8  117.31 269.92 234.81 199.7  162.58  95.13
 222.05 171.11 254.02 238.13 293.26 267.34 241.41 189.26 130.34 276.93
 241.39 205.85 165.54  98.71 240.74 188.21 261.01 245.09 302.89 276.36
 249.83 192.38 129.18 265.26 230.22 195.18 153.46  94.93 255.83 208.76
 251.14 237.03 299.01 272.37 245.74 188.35 127.35 261.04 225.67 190.3
 153.18  94.37 251.6  204.18 246.78 299.85 273.5  247.15 187.57 126.93
 266.01 230.61 195.21 154.28  95.15 252.49 205.13 251.8  237.58 296.33
 270.13 243.94 193.15 130.57 273.21 237.99 202.77 159.98  98.83 249.3
 202.28 259.02 244.83 290.01 263.72 237.42 190.05 127.12 270.2  234.84
 199.47 157.22  97.63 242.74 195.47 255.92 241.64 305.19 278.78 252.37
 194.24 130.16 261.97 226.53 191.09 157.12  95.8  247.63 233.28]

Margen Comercialización (CVm,i,j) [n = 167]: [ 24.86  66.56  63.79  78.71  93.73  50.91 193.88 100.59  22.79  70.27
 112.06  93.08  66.18 107.2  117.73 123.88 181.34 181.03 152.84 190.
  99.58  68.14 106.74 116.1  109.99 171.47 176.93 134.81 100.73  67.93
  59.23  72.81  55.51  84.36  87.68  54.03 186.84  96.57  25.59  57.26
  76.29  53.15  83.19  80.25  59.51 187.01  97.24  28.69  57.57  74.85
  71.31  84.61  83.49  59.31 189.88 100.11  25.96  53.33  68.6   62.36
  84.94  87.95  59.86 188.35  98.98  21.01  54.36  70.47  60.03  82.12
  86.86  51.58 194.41  99.7   21.93  55.82  71.05  55.09  84.99  86.84
  59.96 190.77  54.77  68.07  48.08  80.03  80.62  58.78 195.71  54.91
  70.7   66.88  81.31  85.15  59.32 193.62 100.61  22.97  56.01  67.86
  57.42  82.84  88.42  61.47 193.47 100.08  23.31  27.08  66.43  62.07
  84.13  82.19  30.23 198.34 103.47  24.76  27.27  67.96  51.53  90.43
 121.28  30.66 203.92 107.12  25.48  27.79  66.96  59.41  86.73  30.85
 200.28 105.78  25.43  27.13  65.02  59.92  93.01  29.48 208.21 110.22
  23.97  25.46  56.44  56.19  85.52  29.58 217.19 111.83  22.44  25.07
  49.99  27.01 209.5  108.1   22.22  26.39  57.43  58.01  28.98 208.5
 108.46  23.88  26.31  58.36  50.56  29.03  23.73]

Costo G, T, Pérdidas (PRn,m) [n = 234]: [72.49 24.32 23.65 70.63 29.69 25.29 86.08 37.95 28.58 70.76 29.96 58.26
 19.73 19.3  57.36 24.73 21.23 83.2  36.15 26.85 56.8  24.58 22.44 58.28
 19.83 19.39 57.43 24.87 21.36 83.1  36.18 26.92 56.85 24.7  22.56 59.39
 19.82 58.46 24.96 21.34 84.72 36.46 26.95 57.88 24.8  22.58 67.93 22.79
 22.28 67.23 28.71 24.54 85.53 37.69 28.41 71.86 30.89 28.17 73.38 24.04
 23.46 72.51 30.43 25.87 83.99 36.83 27.67 69.35 29.54 26.89 58.96 20.2
 19.74 57.81 24.72 21.14 84.8  37.51 28.33 55.87 24.59 22.49 59.15 19.72
 19.25 57.93 24.28 20.66 85.03 37.09 27.79 55.99 24.17 22.04 59.71 19.79
 19.31 58.39 24.36 20.71 85.13 37.05 27.72 64.71 27.46 24.97 60.64 25.25
 21.46 82.31 35.95 58.69 25.16 22.92 69.38 23.32 22.74 67.87 24.37 85.96
 37.82 28.47 65.56 28.39 25.01 70.5  23.11 68.84 25.58 28.49 85.31 37.17
 27.8  66.53 28.3  25.76 67.72 22.51 21.9  66.04 27.6  23.47 86.23 37.71
 28.27 63.92 27.47 25.04 70.13 23.35 22.68 68.1  28.42 24.16 83.41 36.7
 66.09 28.38 71.62 24.45 69.56 30.14 25.92 87.34 39.22 29.86 67.63 30.18
 27.68 63.77 21.87 61.79 26.23 22.43 81.67 37.08 27.85 52.48 24.19 22.61
 55.   18.89 18.33 53.22 19.32 80.02 36.03 26.93 45.28 20.91 19.54 55.37
 19.1  18.53 54.2  23.44 20.17 79.58 35.92 45.73 21.17 19.81 60.44 20.6
 19.96 58.9  25.23 21.66 79.34 35.77 26.76 49.78 22.83 21.33 60.3  20.25
 19.6  58.77 24.91 21.32 79.67 35.32 26.47 49.59 22.5  20.99 61.83 21.5
 20.85 60.29 26.19 51.08 23.8  22.27]

Restricciones (Rm) [n = 44]: [ 3.71  9.9  18.49 19.21 18.1   9.76 10.17 10.98  9.72  9.52 11.37  8.31
  6.7  37.14  7.28 22.85 36.71 26.57 24.01 28.88 25.19 11.01 31.79  1.56
 11.28  4.44  1.68  4.96  1.67 22.07  3.72 22.46 18.13 43.2  23.67 38.01
 40.46 39.5  45.23 49.18 75.11 46.81 69.22 30.46]

COT [n = 93]: [  0.    41.7   38.93  56.79  71.81  28.99  94.87  32.69  46.27  28.97
  52.73  56.05  22.4   31.89  50.92  27.78  56.37  53.43  29.34  46.62
  43.08  52.95  51.83  27.65  89.37  30.87  46.14  39.9   56.63  59.64
  31.55  94.71  30.78  46.89  36.45  56.45  61.19  25.91  92.22  32.98
  48.11  32.15  60.01  61.86  34.98  94.39  31.4   44.7   24.71  53.47
  54.06  32.22  93.01  30.33  46.12  42.3   53.13  56.97  31.14  92.66
  42.72  32.28  54.29  56.87  32.92  93.21  39.35  34.99  53.9   51.96
  96.81  40.69  24.26  59.77  90.62  94.5   39.17  31.62  55.88  37.89
  32.79  63.53  97.99  30.98  30.73  55.94 101.4   34.34  24.92  57.35
  31.04  32.05  24.25]

Cfm,j ($/fact.) [n = 78]: [9.8130e+00 1.6160e+01 1.0140e+01 9.0510e+00 9.2860e+00 1.5291e+01
 9.5940e+00 8.5650e+00 9.3280e+00 1.5361e+01 9.6390e+00 8.6040e+00
 9.4140e+00 1.5502e+01 9.7270e+00 8.6830e+00 9.5600e+00 1.5742e+01
 9.8320e+00 8.8180e+00 9.6400e+00 1.5874e+01 9.9020e+00 8.8910e+00
 9.6810e+00 1.5941e+01 9.9600e+00 8.9290e+00 9.7120e+00 1.5992e+01
 1.0002e+01 8.9580e+00 9.7310e+00 1.6025e+01 1.0035e+01 8.9760e+00
 1.0055e+01 9.7550e+03 1.6064e+04 1.0079e+04 8.9980e+03 9.7420e+00
 1.6043e+01 1.0079e+01 8.9860e+00 9.7690e+00 1.6086e+01 1.0093e+01
 9.0100e+00 9.9060e+00 1.6311e+01 9.1360e+00 1.0018e+01 1.6496e+01
 1.0235e+01 9.2400e+00 1.0071e+01 1.6583e+01 1.0351e+01 9.3940e+00
 1.0137e+01 1.6693e+01 1.0406e+01 9.5060e+00 1.0172e+01 1.6750e+01
 1.0474e+01 9.6010e+00 1.0181e+01 1.6764e+01 1.0508e+01 1.0208e+01
 1.6810e+01 1.0519e+01 9.6770e+00 1.0227e+01 1.6841e+01 9.7210e+00]

Año_ [n = 2]: ['2025' '2024']

Num_Periodo [n = 12]: ['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12']

In [49]:
df.isnull().sum()

Año                                  0
Periodo                              0
Operador de red                      0
Nivel                                0
CU Total                             0
Costo Compra (Gm,i)                  0
Cargo Transporte STN (Tm)            0
Cargo Transporte SDL (Dn,m)          0
Margen Comercialización (CVm,i,j)    0
Costo G, T, Pérdidas (PRn,m)         0
Restricciones (Rm)                   0
COT                                  0
Cfm,j ($/fact.)                      0
dtype: int64

In [50]:
df.isna().sum()

Año                                  0
Periodo                              0
Operador de red                      0
Nivel                                0
CU Total                             0
Costo Compra (Gm,i)                  0
Cargo Transporte STN (Tm)            0
Cargo Transporte SDL (Dn,m)          0
Margen Comercialización (CVm,i,j)    0
Costo G, T, Pérdidas (PRn,m)         0
Restricciones (Rm)                   0
COT                                  0
Cfm,j ($/fact.)                      0
dtype: int64

In [51]:
df.isna().sum()

Año                                  0
Periodo                              0
Operador de red                      0
Nivel                                0
CU Total                             0
Costo Compra (Gm,i)                  0
Cargo Transporte STN (Tm)            0
Cargo Transporte SDL (Dn,m)          0
Margen Comercialización (CVm,i,j)    0
Costo G, T, Pérdidas (PRn,m)         0
Restricciones (Rm)                   0
COT                                  0
Cfm,j ($/fact.)                      0
dtype: int64

In [52]:
df.duplicated().sum()

np.int64(0)

In [66]:
# Eliminar comas en los números

df['Año'] = df['Año'].str.replace(r'[,]', '', regex=True)
df['CU Total'] = df['CU Total'].str.replace(r'[,]', '', regex=True)
df['Cfm,j ($/fact.)'] = df['Cfm,j ($/fact.)'].str.replace(r'[,]', '', regex=True)

In [67]:
# Cambio del tipo de variables

df['Año'] = df['Año'].astype('int')
df['CU Total'] = df['CU Total'].astype('float')
df['Cfm,j ($/fact.)'] = df['Cfm,j ($/fact.)'].astype('float')
df.dtypes

Año                                    int64
Periodo                               object
Operador de red                       object
Nivel                                 object
CU Total                             float64
Costo Compra (Gm,i)                  float64
Cargo Transporte STN (Tm)            float64
Cargo Transporte SDL (Dn,m)          float64
Margen Comercialización (CVm,i,j)    float64
Costo G, T, Pérdidas (PRn,m)         float64
Restricciones (Rm)                   float64
COT                                  float64
Cfm,j ($/fact.)                      float64
dtype: object

In [69]:
# Limpieza de fechas

df['Num_Periodo'] = (df['Periodo']
                       .str.replace('Enero', '1')
                       .str.replace('Febrero', '2')
                       .str.replace('Marzo', '3')
                       .str.replace('Abril', '4')
                       .str.replace('Mayo', '5')
                       .str.replace('Junio', '6')
                       .str.replace('Julio', '7')
                       .str.replace('Agosto', '8')
                       .str.replace('Septiembre', '9')
                       .str.replace('Octubre', '10')
                       .str.replace('Noviembre', '11')
                       .str.replace('Diciembre', '12')
                       )

df.head()

,Año,Periodo,Operador de red,Nivel,CU Total,"Costo Compra (Gm,i)",Cargo Transporte STN (Tm),"Cargo Transporte SDL (Dn,m)","Margen Comercialización (CVm,i,j)","Costo G, T, Pérdidas (PRn,m)",Restricciones (Rm),COT,"Cfm,j ($/fact.)",Num_Periodo
0,2025,Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad OR),810.46,372.46,56.03,280.91,24.86,72.49,3.71,0.00,9.813,1
1,2025,Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad Compartida),787.37,372.46,56.03,257.82,24.86,72.49,3.71,0.00,9.813,1
2,2025,Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad Cliente),764.29,372.46,56.03,234.73,24.86,72.49,3.71,0.00,9.813,1
3,2025,Enero,ENEL Bogotá - Cundinamarca,NIVEL II,691.89,372.46,56.03,168.80,66.56,24.32,3.71,41.70,9.813,1
4,2025,Enero,ENEL Bogotá - Cundinamarca,NIVEL III,633.30,372.46,56.03,113.66,63.79,23.65,3.71,38.93,9.813,1

In [71]:
# Pasarlo a formato fecha

df['Fecha'] = pd.to_datetime(
    dict(year=df['Año'], month=df['Num_Periodo'], day=1)
).dt.to_period('M')

df.head()

,Año,Periodo,Operador de red,Nivel,CU Total,"Costo Compra (Gm,i)",Cargo Transporte STN (Tm),"Cargo Transporte SDL (Dn,m)","Margen Comercialización (CVm,i,j)","Costo G, T, Pérdidas (PRn,m)",Restricciones (Rm),COT,"Cfm,j ($/fact.)",Num_Periodo,Fecha
0,2025,Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad OR),810.46,372.46,56.03,280.91,24.86,72.49,3.71,0.00,9.813,1,2025-01
1,2025,Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad Compartida),787.37,372.46,56.03,257.82,24.86,72.49,3.71,0.00,9.813,1,2025-01
2,2025,Enero,ENEL Bogotá - Cundinamarca,Nivel 1 (Propiedad Cliente),764.29,372.46,56.03,234.73,24.86,72.49,3.71,0.00,9.813,1,2025-01
3,2025,Enero,ENEL Bogotá - Cundinamarca,NIVEL II,691.89,372.46,56.03,168.80,66.56,24.32,3.71,41.70,9.813,1,2025-01
4,2025,Enero,ENEL Bogotá - Cundinamarca,NIVEL III,633.30,372.46,56.03,113.66,63.79,23.65,3.71,38.93,9.813,1,2025-01